### ISSUE TITLE
Using emoticons adds a bunch of extra text to my chat message but only in YatA

### ISSUE THREAD

**Issue by eckerdj7** [HiDeoo/YaTA#48] opened 2020-07-23 15:58 UTC
**Describe the bug**

Whenever I type a regular emoticon, like :) or <3, the YatA chat shows what looks to be the rest of the html tag, like this:
:)" data-id="1" data-provider="twitch" src="https://static-cdn.jtvnw.net/emoticons/v1/1/1.0" srcset="https://static-cdn.jtvnw.net/emoticons/v1/1/1.0 1x,https://static-cdn.jtvnw.net/emoticons/v1/1/2.0 2x,https://static-cdn.jtvnw.net/emoticons/v1/1/3.0 4x" alt=":)" />

**To Reproduce**

1. Go to any channel chat.
2. Type any regular emoticon into the chat message or choose it from the emote menu (something like :) , :P , or <3)
3. Send the message.

**Expected behavior**

To see just the emoticon.

**Screenshots**

![image](https://user-images.githubusercontent.com/4165786/88308275-dbc0bd80-ccda-11ea-9eb3-50376feb419a.png)

**Environment**

| Software         | Version
| ---------------- | -------
| YaTA             | 1.14.0
| Browser          | Chrome 84.0.4147.89
| Operating System | Windows NT 10.0

**Comment by HiDeoo** [comment] 2020-07-25 10:58
Thanks for the report.

Closing as duplicate of #46 which contains more infos and some updates. TLDR: I'm not able to repro yet the issue altho according to some other reports (for the official Twitch chat), it may be a Twitch issue.

**Closed as completed by HiDeoo** 2020-07-25 10:58 UTC
